#version: "3" #this gives obsolete warning
services:
  db:
    build: ./pg-vec-geo
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5436:5432"
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data
      - ./data/ingest_data:/ingest_data
  app:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      environment:
        - DB_HOST=db
        - DB_PORT=5432
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DATA_DIR=/app/data
      ports:
        - "8000:8000"
      depends_on:
        - db
      volumes:
        - ./data:/app/data

volumes:
  pg-data:
    external: false
