import pandas as pd
import numpy as np
from sqlalchemy import create_engine, Column, Integer, Float, String, ForeignKey
from sqlalchemy.orm import Session, relationship, declarative_base
import sys
from pathlib import Path
from .utils import aggregate_full_net
import decoupler as dc

DB_URL = 'postgresql+psycopg://postgres:postgres@localhost:5436/diffCellSig'

#upstream analyses settings, will have to be passed by user
ORGANISM = 'mouse'
SPLIT_COMPLEXES = False
CONDS = ['Ko', 'Wt']
TF_COND_COLNAME = 'Genotype'

Base = declarative_base() #serves as a factory for mapping Python classes to db tables in an ORM

class Link(Base):
    __tablename__ = 'links'
    id = Column(Integer, primary_key=True, unique=True, autoincrement=True)
    source = Column(Integer, ForeignKey('nodes.id'))
    target = Column(Integer, ForeignKey('nodes.id'))

    #link attributes
    type = Column(String) #link type: LR, TFL, RTF
    weight = Column(Float) #link weight/score this will be different for each link type: LR [0,1], TFL [-1;1], RTF [null, 1]
    significance = Column(Float) #p-value or adjusted p-value, applicable only for LR
    layer = Column(Integer) #1 for TFL, 2 for LR (CCC), 3 for RTF 
    detailed_type = Column(String) 

    #relationships
    from_node = relationship("Node", back_populates="outgoing_links", foreign_keys=[source])
    to_node = relationship("Node", back_populates="incoming_links", foreign_keys=[target])

class Node(Base):
    __tablename__ = 'nodes'
    #nodes attributes
    id = Column(Integer, primary_key=True, unique=True, autoincrement=True)
    name = Column(String, nullable=False)
    celltype = Column(String, nullable=False) 
    moltype = Column(String, nullable=False) #general type: ligand, receptor, TF     # TODO: how to solve bothLR nodes? currently annotated as bothLR from function called in aggregate_full_net
    intrascore = Column(Float) #for receptor nodes
    verbose_id = Column(String, unique=True) #name__cellType to uniquely identify nodes before ids are generated
    #relationships
    outgoing_links = relationship("Link", back_populates="from_node", foreign_keys=[Link.source])
    incoming_links = relationship("Link", back_populates="to_node", foreign_keys=[Link.target])



def main():
    cwd = Path(__file__).parent.resolve()
    try:
        ccc = pd.read_csv(cwd / 'data' / 'CCC.csv') # CCI results
        tfl = pd.read_csv(cwd / 'data' / 'TFL.csv') #TF activity results
    except Exception as e:
        print('Unable to access csv file', repr(e))
        sys.exit(1)
    print('CSV files successfully loaded')

    if Path.exists(cwd / 'data' / 'sanitizeCelltypes.csv'):
        from .utils import sanitizeCelltypes
        ccc, tfl = sanitizeCelltypes(ccc, tfl, ref_file = cwd / 'data' / 'sanitizeCelltypes.csv')
    
    ccc_celltypes = set(ccc['sender']).union(set(ccc['receiver']))
    tfl_celltypes = set(tfl['cellType'])

    if ccc_celltypes.difference(tfl_celltypes):
        print('Warning: cell types in CCC and TFL results do not match')
        sys.exit(1)
    
    tf_db = dc.get_collectri(organism = ORGANISM, split_complexes = SPLIT_COMPLEXES)
    nodes, links = aggregate_full_net(ccc, tfl, tf_db, conditions = CONDS, cond_colname = TF_COND_COLNAME)

    #NaN from pandas or numpy cannot be serialized, causing Internal Server Errors
    links = links.replace({np.nan: None})
    nodes = nodes.replace({np.nan: None})

    #create db engine
    try:
        engine = create_engine(DB_URL, echo=True) 
        print('Database engine created')
    except Exception as e:
        print('Unable to access database', repr(e))
        sys.exit(1)
    
    # delete old tables #not sure if this is necessary
    Base.metadata.drop_all(engine, tables=[Base.metadata.tables["nodes"], Base.metadata.tables["links"]])
    # Create new tables
    Base.metadata.create_all(engine)
    print('Tables created (if not already present)')

    #populate tables
    session = Session(engine)
    print('Session created')

    try: 
        #iterate through dataframes and add to session
        #ids are automatically generated by sqlalchemy, with autoincrement
        print('\nPopulating tables...')
        for i,row in nodes.iterrows():
            v = Node(name=row['name'], celltype=row['celltype'], moltype=row['moltype'], intrascore=row['intrascore'], verbose_id = f"{row['name']}__{row['celltype']}__{row['moltype']}")
            session.add(v)
        try:
            session.flush() #this creates ids
            print('Vertices added to session')
        except Exception as e:
            session.rollback()
            raise ValueError('Unable to flush session after adding nodes\n', repr(e))
        
        db_nodes = session.query(Node).all() 
        print(f'Number of nodes in db: {len(db_nodes)}')
        print(f'Number of nodes in dataframe: {len(nodes.index)}')
        node_map = { f"{n.name}__{n.celltype}__{n.moltype}": n.id for n in db_nodes }
        print('Node map created')

        links['source'] = links['from'].map(node_map)
        links['target'] = links['to'].map(node_map)
        print('Links mapped to nodes ids')

        for i, row in links.iterrows():
            if row['type'] == 'TFL':
                if row['weight'] > 0:
                    dtype = 'TF promotes expression of target ligand-encoding gene'
                else:
                    dtype = 'TF inhibits expression of target ligand-encoding gene'
            else:
                dtype = row['type']

            e = Link(type=row['type'], weight=row['weight'], significance=row['significance'], layer=row['layer'], source = row['source'], target = row['target'], detailed_type = dtype)
            session.add(e)
        print('Links added to session')

    except Exception as e:
        session.rollback() 
        print('Unable to populate tables\n', repr(e))
    else:
        session.commit() #commit only onces: doesnt make sense to commit separately for nodes and links
        print('Tables populated')


if __name__ == '__main__':
    main()


