[project]
name = "diffcellsig"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "decoupler>=2.1.4",
    "fastapi[standard]>=0.128.0",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "neo4j>=6.1.0",
    "networkx>=3.6.1",
    "omnipath>=1.0.12",
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.40.0",
]
